06-12-2017 17:50:54
Test1 : passed
06-12-2017 17:50:54
Test2 : failed
06-12-2017 17:50:54
Test3 : failed with message "Exception has been thrown by the target of an invocation."
